const {test}=require('node:test');
const assert=require('node:assert/strict');
const {decode,Detector}=require('../app/src/main/assets/core.js');
function sample(seq,overrides={}){return {seq,temp:25,smoke:300,flame:false,gps:true,sensors:true,...overrides};}
test('three consecutive two-sensor readings trigger one alarm; five normal rearm',()=>{const d=new Detector();let alarms=0;for(let i=0;i<8;i++)alarms+=Number(d.accept(sample(i,{temp:80,smoke:2200}),i*1000).alarm);assert.equal(alarms,1);for(let i=8;i<13;i++)d.accept(sample(i),i*1000);assert.equal(d.active,false);for(let i=13;i<16;i++)d.accept(sample(i,{flame:true,temp:80}),i*1000);assert.equal(d.active,true);});
test('single sensor does not confirm fire',()=>{const d=new Detector();for(let i=0;i<10;i++)assert.equal(d.accept(sample(i,{flame:true}),i*1000).state,'suspect');assert.equal(d.active,false);});
test('duplicate, old, wrapped sequence',()=>{const d=new Detector();d.accept(sample(65535),0);assert.equal(d.accept(sample(65535),1).ignored,true);assert.equal(d.accept(sample(0),1000).state,'normal');assert.equal(d.accept(sample(65534),2000).ignored,true);assert.equal(d.last,1000);});
test('stale connection interrupts confirmation, retains existing alarm',()=>{const d=new Detector();d.accept(sample(0,{temp:80,flame:true}),0);d.accept(sample(1,{temp:80,flame:true}),1000);assert.equal(d.stale(6001),true);assert.equal(d.accept(sample(2,{temp:80,flame:true}),7000).alarm,false);d.accept(sample(3,{temp:80,flame:true}),8000);assert.equal(d.accept(sample(4,{temp:80,flame:true}),9000).alarm,true);assert.equal(d.stale(15000),true);assert.equal(d.active,true);});
test('sensor fault cannot clear alarm or count toward confirmation',()=>{const d=new Detector();for(let i=0;i<3;i++)d.accept(sample(i,{temp:80,flame:true}),i*1000);for(let i=3;i<9;i++)assert.equal(d.accept(sample(i,{sensors:false}),i*1000).state,'fault');assert.equal(d.active,true);});
test('decode little endian packet and reject malformed/range errors',()=>{const b=new Uint8Array(20),v=new DataView(b.buffer);b[0]=1;b[1]=7;v.setUint16(2,42,true);v.setInt16(4,7650,true);v.setUint16(6,2300,true);v.setInt32(8,432389490,true);v.setInt32(12,768897090,true);v.setInt16(16,50,true);b[18]=92;const t=decode(b);assert.equal(t.temp,76.5);assert.equal(t.lat,43.238949);assert.equal(t.altitude,5);assert.equal(t.flame,true);assert.throws(()=>decode(b.slice(1)));b[18]=101;assert.throws(()=>decode(b));b[18]=92;b[0]=2;assert.throws(()=>decode(b));});
